env:
  browser: true
  node: true
  commonjs: true
  es6: true
globals:
  $: true
  jquery: true
  jQuery: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
